reset to v3.5.0-RC1

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,6 +5,7 @@ on:
   push:
     branches:
       - master
+      - 3.5.x
       - 3.4.x
       - 3.3.x
       - 3.2.x
@@ -15,109 +16,103 @@ jobs:
     strategy:
       matrix:
         system: ["ubuntu-20.04"]
-        jvm: ["adopt@1.8"]
-        scala: ["2.13.6", "2.12.15"]
-        verilator: ["4.204"]
+        jvm: ["8"]
+        scala: ["2.13.10", "2.12.17"]
         espresso: ["2.4"]
+        circt: ["firtool-1.31.0"]
     runs-on: ${{ matrix.system }}
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Install Z3
-        if: matrix.system == 'ubuntu-20.04'
-        run: |
-          sudo apt-get install -y z3
-          z3 --version
-
-      - name: Cache Verilator ${{ matrix.verilator }}
-        uses: actions/cache@v2.1.6
-        id: cache-verilator
-        with:
-          path: verilator-${{ matrix.verilator }}
-          key: ${{ matrix.system }}-verilator-${{ matrix.verilator }}
-      - name: Compile Verilator ${{ matrix.verilator }}
-        if: steps.cache-verilator.outputs.cache-hit != 'true'
-        run: |
-          wget https://github.com/verilator/verilator/archive/refs/tags/v${{ matrix.verilator }}.tar.gz
-          tar xvf v${{ matrix.verilator }}.tar.gz
-          cd verilator-${{ matrix.verilator }}
-          autoconf
-          ./configure
-          make
-      - name: Install Verilator ${{ matrix.verilator }}
-        run: |
-          cd verilator-${{ matrix.verilator }}
-          sudo make install
-          verilator --version
-
+        uses: actions/checkout@v3
+      - name: Install Tabby OSS Cad Suite
+        uses: ./.github/workflows/setup-oss-cad-suite
       - name: Install Espresso
-        run: |
-          cd /tmp
-          wget https://github.com/chipsalliance/espresso/releases/download/v${{ matrix.espresso }}/x86_64-linux-gnu-espresso
-          chmod +x x86_64-linux-gnu-espresso
-          sudo mv x86_64-linux-gnu-espresso /usr/local/bin/espresso
-          espresso || true
-
-      - name: Setup Scala
-        uses: olafurpg/setup-scala@v10
+        uses: ./.github/workflows/install-espresso
         with:
+          version: ${{ matrix.espresso }}
+      - name: Setup Scala
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'adopt'
           java-version: ${{ matrix.jvm }}
-      - name: Cache Scala
-        uses: coursier/cache-action@v5
-      - name: Documentation (Scala 2.12 only)
-        if: startsWith(matrix.scala, '2.12')
-        run: sbt ++${{ matrix.scala }} docs/mdoc
+          cache: 'sbt'
+      - name: Install CIRCT
+        uses: ./.github/workflows/install-circt
+        with:
+          version: ${{ matrix.circt }}
       - name: Test
-        run: sbt ++${{ matrix.scala }} test noPluginTests/test
+        run: sbt ++${{ matrix.scala }} test
       - name: Binary compatibility
         run: sbt ++${{ matrix.scala }} mimaReportBinaryIssues
+
+  doc:
+    name: Formatting
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup Scala
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+          cache: 'sbt'
+      - name: Install CIRCT
+        uses: ./.github/workflows/install-circt
+      - name: Check Formatting
+        run: sbt scalafmtCheckAll
 
   integration:
     name: Integration Tests (w/ chiseltest)
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
-      - name: Install Verilator and Z3
-        run: |
-          sudo apt-get install -y verilator z3
-          verilator --version
-          z3 --version
+        uses: actions/checkout@v3
+      - name: Install Tabby OSS Cad Suite
+        uses: ./.github/workflows/setup-oss-cad-suite
       - name: Install Espresso
-        run: |
-          cd /tmp
-          wget https://github.com/chipsalliance/espresso/releases/download/v2.4/x86_64-linux-gnu-espresso
-          chmod +x x86_64-linux-gnu-espresso
-          sudo mv x86_64-linux-gnu-espresso /usr/local/bin/espresso
-          espresso || true
+        uses: ./.github/workflows/install-espresso
       - name: Setup Scala
-        uses: olafurpg/setup-scala@v10
+        uses: actions/setup-java@v3
         with:
-          java-version: "adopt@1.11"
-      - name: Cache Scala
-        uses: coursier/cache-action@v5
+          distribution: 'adopt'
+          java-version: '11'
+          cache: 'sbt'
       - name: Integration Tests
+        # This is here instead of on the whole job because, if a job is skipped, so are dependent jobs.
+        # If this job were skipped, all_tests_passed would be skipped too.
+        # By having this "if" here, this job returns success so that all_tests_passed will succeed too.
+        if: github.event_name != 'pull_request' ||
+          ! contains(github.event.pull_request.labels.*.name, 'Skip chiseltest')
         run: sbt integrationTests/test
 
-  # Sentinel job to simplify how we specify which checks need to pass in branch
-  # protection and in Mergify
-  #
-  # When adding new jobs, please add them to `needs` below
-  all_tests_passed:
-    name: "all tests passed"
-    needs: [ci, integration]
+  std:
+    name: Standard Library Tests
     runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        scala: [ "2.13.10", "2.12.17" ]
     steps:
-      - run: echo Success!
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Install Tabby OSS Cad Suite
+        uses: ./.github/workflows/setup-oss-cad-suite
+      - name: Setup Scala
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+          cache: 'sbt'
+      - name: Check Formatting (Scala 2.12 only)
+        if: startsWith(matrix.scala, '2.12')
+        run: sbt ++${{ matrix.scala }} standardLibrary/scalafmtCheckAll
+      - name: Unit Tests
+        run: sbt ++${{ matrix.scala }} standardLibrary/test
 
-  # sbt ci-release publishes all cross versions so this job needs to be
-  # separate from a Scala versions build matrix to avoid duplicate publishing
-  publish:
-    needs: [all_tests_passed]
-    runs-on: ubuntu-20.04
-    if: github.event_name == 'push'
+  website:
+    name: Build Mdoc & Website
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
@@ -128,10 +123,87 @@ jobs:
           java-version: adopt@1.8
       - name: Cache Scala
         uses: coursier/cache-action@v5
+      - name: Setup Ruby
+        uses: actions/setup-ruby@v1
+      - name: Setup Jekyll
+        run: |
+          gem install jekyll -v 4.2.0
+          gem install jekyll-redirect-from
+      - name: Install CIRCT
+        uses: ./.github/workflows/install-circt
+        #TODO: make the microsite building include building ScalaDoc
+      - name: Build the docs
+        run: sbt doc
+      - name: Build the microsite
+        run: make -C website
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Tar built website
+        run: tar zcf website.tar.gz website/docs/target/site
+      - name: Share Built Website
+        uses: actions/upload-artifact@v3
+        with:
+          name: website
+          path: website.tar.gz
+
+  # Sentinel job to simplify how we specify which checks need to pass in branch
+  # protection and in Mergify. This job checks that all jobs were successful.
+  #
+  # When adding new jobs, please add them to `needs` below
+  check-tests:
+    name: "check tests"
+    needs: [ci, integration, std, doc, website]
+    runs-on: ubuntu-20.04
+    if: success() # only run if all tests have passed
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        run: echo "success=true" >> $GITHUB_OUTPUT
+
+  # Related to check-tests above, this job _always_ runs (even if tests fail
+  # and thus check-steps is skipped). This two sentinel job approach avoids an
+  # issue where failing tests causes a single sentinel job to be skipped which
+  # counts as passing for purposes of branch protection.
+  #
+  # See: https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  all_tests_passed:
+    name: "all tests passed"
+    runs-on: ubuntu-20.04
+    if: always() # Always run so that we never skip this check
+    needs: check-tests
+      # Pass only if check-tests set its output value
+    steps:
+      - run: |
+          PASSED="${{ needs.check-tests.outputs.success }}"
+          if [[ $PASSED == "true" ]]; then
+            echo "### All tests passed! :rocket:" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          else
+            echo "### One or more tests FAILED! :bangbang:" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+  # sbt ci-release publishes all cross versions so this job needs to be
+  # separate from a Scala versions build matrix to avoid duplicate publishing
+  publish:
+    needs: [all_tests_passed]
+    runs-on: ubuntu-20.04
+    if: (github.event_name == 'push' && github.ref_name != 'website-test')
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup Scala
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'adopt'
+          java-version: '8'
+          cache: 'sbt'
       - name: Setup GPG (for Publish)
         uses: olafurpg/setup-gpg@v3
       - name: Publish
-        run: sbt ci-release
+        run: sbt -DdisableFatalWarnings ci-release
         env:
           PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
           PGP_SECRET: ${{ secrets.PGP_SECRET }}
@@ -139,3 +211,21 @@ jobs:
           SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
 
 
+  deploy_website:
+    name: Deploy Website
+    runs-on: ubuntu-latest
+    needs: [all_tests_passed]
+    if: (github.event_name == 'push') && (github.ref_type == 'branch') && ((github.ref_name == 'website-test') || (github.ref_name == 'master'))
+    steps:
+      - name: Download built website
+        uses: actions/download-artifact@v3
+        with:
+          name: website
+      - name: Untar built website
+        run: tar zxf website.tar.gz
+      - name: Deploy Website to GitHub Pages (From Master Branch)
+        uses: JamesIves/github-pages-deploy-action@3.7.1
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH: gh-pages
+          FOLDER: website/docs/target/site
